---
title: "house_num_challenge"
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4.5
    theme: cosmo
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE)
```


```{r set_up}
#パッケージのインストールと読み込み
#持ってないパッケージはインストールする
targetPackages <- c('knitr','DBI','RPostgreSQL','tidyverse',"reshape2","lubridate","dbplot","DT") 
newPackages <- targetPackages[!(targetPackages %in% installed.packages()[,"Package"])]
if(length(newPackages)) install.packages(newPackages, repos = "http://cran.us.r-project.org")
for(package in targetPackages) library(package, character.only = T)


theme_set(theme_bw(base_family = "HiraKakuPro-W3"))

source("psql.R")

```


```{r get_data}
play <- con %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_play_p_cv")) 
orgn <- con %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_orgn_p_cv"))
prof <- con %>% 
  tbl(from = dbplyr::in_schema("processed", "profiledata"))


#play1<- dbGetQuery(con,"SELECT * FROM processed.tv_play_p_cv")
#orgn1 <- dbGetQuersy(con,"SELECT * FROM processed.tv_orgn_p_cv")
#prof1 <- dbGetQuery(con,"SELECT * FROM prcessed.profiledata")

```

#日程ごとのログ数
```{r 日程ごとのログ数}
 houseDate <- dbGetQuery(con,"SELECT  
 	distinct(br_date),
 	count(br_date)
 FROM
 	processed.tv_orgn_p_cv
 group by
  br_date")

 head(houseDate) %>%
   kable()
 
 summary(houseDate) %>%
   kable()
 
 
houseDate60000 <- dbGetQuery(con,"  
SELECT  
 	distinct(br_date),
 	count(br_date),
	count(distinct(house_num))
FROM
 	processed.tv_orgn_p_cv
group by 
	br_date
HAVING
 	count(br_date) > 60000
ORDER BY
 	count(br_date) DESC;")

colnames(houseDate60000)<- c("date","log count","house count")

houseDate60000 %>%
  kable() 
```
  
年末年始はログの数が多い割には観測世帯数が少なかった.  
帰省などが関係あるかも.


#世帯Noごとの終了, 開始, ログ日数, ログ数
```{r 世帯Noごとの終了, 開始, ログ日数, ログ数}
houseDetail <- dbGetQuery(con,"
SELECT
	distinct(house_num),
	max(br_date),
	min(br_date),
  count(distinct(br_date)),
	count(br_date)

FROM
	processed.tv_orgn_p_cv
group by (house_num)")

head(houseDetail) %>%
  kable()
```

#日程ごとのサンプル数
```{r 日程ごとのサンプル数}
sample_num<- dbGetQuery(con,"
SELECT
	distinct(sample_date),
	count(sample_date)

FROM	
	processed.tv_sample_p_cv

GROUP BY
	tv_sample_p_cv.sample_date;
")


sample_numP <-
  ggplot(sample_num, aes(x = sample_date, y = count))+
  geom_line()+
  ylim(c(5000,5300))

sample_numP
```

#誰がいつサンプリングされたのか
```{r 誰がいつサンプリングされたのか}
sample_att<- dbGetQuery(con,"
SELECT
	house_num,
	sample_date
FROM	
	processed.tv_sample_p_cv
GROUP BY
	house_num,
	sample_date
ORDER BY
  house_num,
	sample_date DESC;")

head(sample_att) %>%
  kable()

sample_attP<-
  ggplot(sample_att, aes(x = sample_date, y = house_num, color = house_num))+
  geom_bin2d(binwidth = c(1,1))# + ylim(c(0,20))+xlim(c(as.Date('2017-03-28'),as.Date('2017-04-20')))

sample_attP
```

#再生ログと閲覧ログの一致確認
  
リアルタイムのログ数と日程順に並べた最初の数行を示す.
```{r realtime1}
time9 <- dbGetQuery(con,"
SELECT
	br_start_datetime,
	house_num
FROM
	processed.tv_orgn_p_cv
WHERE
	data_agg_type = 9
ORDER BY 
	br_start_datetime;
")
nrow(time9)
head(time9) %>%
  kable()
```

これを, 家庭数ごとでまとめる.

```{r realtime2}
time9_house <- dbGetQuery(con,"
SELECT
	br_start_datetime,
	count(distinct(house_num))
 FROM
	processed.tv_orgn_p_cv
 WHERE
	data_agg_type = 9
 group by 
	br_start_datetime
ORDER BY 
	br_start_datetime;
")
nrow(time9_house)
head(time9_house) %>%
  kable()

time9_house[time9_house$count > 500,]

```
  
閲覧ログとの一致を考える.

```{r}
#1025万行だから重いよ

time_check <- dbGetQuery(con,"
SELECT 	
	A.br_start_datetime,
	A.house_num
FROM 
(SELECT
	br_start_datetime,
	house_num
FROM
	processed.tv_orgn_p_cv
WHERE
	data_agg_type = 9
ORDER BY 
	br_start_datetime) AS A

LEFT OUTER JOIN 
(SELECT
	timeshift_datetime,
	house_num
FROM
	processed.tv_play_p_cv
WHERE
	(timeshift_datetime > TO_TIMESTAMP('2017/04/03 05:08:59', 'YYYY-MM-DD HH24:MI:SS'))
ORDER BY 
	timeshift_datetime) AS B
ON
  A.br_start_datetime = B.timeshift_datetime
   AND
  A.house_num = B.house_num
ORDER BY 
	A.br_start_datetime;
")

nrow(time_check)
head(time_check)%>%
  kable()
```
  
重複カウントがあるため, こちらの方が数が多く現れてしまった.   
  
  
同じく家庭数で縛って一致を行う

```{r}
time_check1 <- dbGetQuery(con,"
SELECT 	
	A.br_start_datetime,
	C
FROM 
(SELECT
	br_start_datetime,
	count(distinct(house_num)) as C
FROM
	processed.tv_orgn_p_cv
WHERE
	data_agg_type = 9
group by 
	br_start_datetime
ORDER BY 
	br_start_datetime) AS A

LEFT OUTER JOIN 
(SELECT
	timeshift_datetime,
	count(distinct(house_num))
FROM
	processed.tv_play_p_cv
WHERE
	(timeshift_datetime > TO_TIMESTAMP('2017/04/03 05:08:59', 'YYYY-MM-DD HH24:MI:SS'))
group by 
	timeshift_datetime
ORDER BY 
	timeshift_datetime) AS B
ON
  A.br_start_datetime = B.timeshift_datetime
ORDER BY 
	A.br_start_datetime;
   ")

nrow(time_check1)
head(time_check1) %>%
  kable()

time_checkP <- ggplot(time_check, aes(x=time_check$br_start_datetime, y = time_check$house_num))+
geom_point()

time_check1P <- ggplot(time_check1, aes(x=time_check1$br_start_datetime, y = time_check1$c))+
geom_point()

#time_checkP
time_check1P

```

閲覧ログと再生ログが一致した.



  
# おまけ 同じ番組を113回見ていた異常者について
```{r}
ijo1 <- dbGetQuery(con,"

SELECT
	*
FROM
	processed.tv_orgn_p_cv
WHERE
	dataseq = 113;
")

ijo2 <- dbGetQuery(con,"
SELECT
	action_datetime
FROM
	processed.tv_play_p_cv
WHERE
	timeshift_datetime = TO_TIMESTAMP('2017/12/29 23:45:00', 'YYYY-MM-DD HH24:MI:SS')
	and
	house_num = 6702
ORDER BY action_datetime;
")

ijo3 <- dbGetQuery(con,"
SELECT
	*
FROM
	processed.tv_program
WHERE
	(program_start_time = TO_TIMESTAMP('2017/12/29 23:45:00', 'YYYY-MM-DD HH24:MI:SS')
	or
  program_end_time =  TO_TIMESTAMP('2017/12/29 23:45:00', 'YYYY-MM-DD HH24:MI:SS'))
  and
	station_code = 6;
")

ijo1
ijo2
ijo3
```

どうも,2時間近く永遠1分間の再生をしていたらしい.  
異常者というより, リピート再生をつけっぱなしにしてしまった?  

