---
title: "performer"
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4.5
    theme: sandstone 
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE)
```


```{r set_up}
#パッケージのインストールと読み込み
#持ってないパッケージはインストールする
targetPackages <- c('knitr','DBI','RPostgreSQL','tidyverse',"reshape2","lubridate","dbplot","DT","prettydoc") 
newPackages <- targetPackages[!(targetPackages %in% installed.packages()[,"Package"])]
if(length(newPackages)) install.packages(newPackages, repos = "http://cran.us.r-project.org")
for(package in targetPackages) library(package, character.only = T)


theme_set(theme_bw(base_family = "HiraKakuPro-W3"))

source("psql.R")

```

#内容確認
  
- 曜日情報は抜けていたため消去.
- 番組終了時刻はなかったため, 次の番組の開始時間として追加.
- 局コードと各局ごとにシリアルナンバーを振ることで主キー登録.
```{r head_performer, result = "asis"}
performer_tmp3 <- con %>% 
  tbl(from = dbplyr::in_schema("add_data", "performer")) 
data <- performer_tmp3 %>% 
  head(100) %>% 
  collect()

data %>% 
  datatable(style="bootstrap", class="table-condensed", options = list(dom = 'tp',scrollX = TRUE))

```


#カウント
##番組情報ベース
  
- NHK系の出演者情報はないため民放5局でチェック.
- 期間は tv_program にあわせた.  

```{r add data の件数}
count0 <- dbGetQuery(con,"
SELECT
	*
FROM
	processed.tv_program as T
LEFT JOIN
	(SELECT
		*
	FROM
	 	add_data.performer_tmp3
	WHERE
		(br_start_datetime_crow >= '20170403050000'
	 AND
		br_start_datetime_crow <= '20180402045900')
	) as A
ON
	(A.station_code = T.station_code
	AND
	A.br_start_datetime_crow <= T.program_start_time
	AND
	A.br_end_datetime_crow > T.program_start_time)
WHERE
	T.station_code <= 5
LIMIT 10;")

count0 %>%
  kable()

```

##局ごとにカウント
  
- 全58812行

```{r}
count1 <- dbGetQuery(con,"
SELECT
	distinct(T.station_code),
	count(T.station_code)
FROM
	processed.tv_program as T
LEFT JOIN
	(SELECT
		*
	FROM
	 	add_data.performer_tmp3
	WHERE
		br_start_datetime_crow >= '20170403050000'
	 AND
		br_start_datetime_crow <= '20180402045900'
	) as A
ON
	(A.station_code = T.station_code
	AND
	A.br_start_datetime_crow <= T.program_start_time
	AND
	A.br_end_datetime_crow > T.program_start_time)
WHERE
	T.station_code <= 5
GROUP BY
	T.station_code;
")


count1 %>%
  kable()

```

##かぶる番組に関して

```{r}
count2 <- dbGetQuery(con,"
SELECT
	A.station_code,
  A.serial_num,
  A.br_start_datetime_crow,
  T.program_start_time,
  A.program_name_crow,
  T.program_name,
  A.regular
FROM
	processed.tv_program as T
LEFT JOIN
	(SELECT
		*
	FROM
	 	add_data.performer_tmp3
	WHERE
		(br_start_datetime_crow >= '20170403050000'
	 AND
		br_start_datetime_crow <= '20180402045900')
	) as A
ON
	(A.station_code = T.station_code
	AND
	A.br_start_datetime_crow <= T.program_start_time
	AND
	A.br_end_datetime_crow > T.program_start_time)
WHERE
	T.station_code <= 5
ORDER BY
	T.station_code,
	A.serial_num,
  T.program_start_time
LIMIT 5;
")

count2 %>%
  kable()

```






