---
title: "profile sample"
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4.5
    theme: sandstone 
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE)
```


```{r set_up}
#パッケージのインストールと読み込み
#持ってないパッケージはインストールする
targetPackages <- c('knitr','DBI','RPostgreSQL','tidyverse',"reshape2","lubridate","dbplot","DT","prettydoc") 
newPackages <- targetPackages[!(targetPackages %in% installed.packages()[,"Package"])]
if(length(newPackages)) install.packages(newPackages, repos = "http://cran.us.r-project.org")
for(package in targetPackages) library(package, character.only = T)


theme_set(theme_bw(base_family = "HiraKakuPro-W3"))

source("psql.R")

```



```{r}
getwd()
x <- read.csv("sample.csv", header=T ,fileEncoding = "utf-8")
head(x)%>%
  kable
```

#性別
```{r}
#sex
sex_count = dplyr::count(x,sex)
sex <- c("male", "female")
sex_count <- cbind(sex,sex_count )
sex_count[,2] <-NULL
sex_count %>%
  kable
sex_countP <-
  ggplot(sex_count, aes(x = sex, y = n))+
  geom_bar(stat = "identity",col=c("skyblue","pink"),,fill=c("skyblue","pink"))+
  labs(title = "ユーザの性別")

sex_countP

```

#婚姻
```{r}
#marriage
marriage_count = dplyr::count(x,marriage)
marriage <- c("未婚", "既婚")
marriage_count <- cbind(marriage,marriage_count )
marriage_count[,2] <-NULL
marriage_count %>%
  kable
marriage_countP <-
  ggplot(marriage_count, aes(x = marriage, y = n))+
  geom_bar(stat = "identity",col=c("skyblue","pink"),,fill=c("skyblue","pink"))+
  labs(title = "婚姻情報")

marriage_countP
```

##円グラフ
```{r}
par(mfrow=c(1,2)) 
pie(sex_count$n, labels=c("male","female"),col=c("skyblue","pink"), clockwise=T, border="#ffffff",main="性別")
pie(marriage_count$n, labels=c("未婚","既婚"),col=c("skyblue","pink"), clockwise=T, border="#ffffff",main="婚姻情報")

```

#年齢
```{r}
#age
age_summarize = dplyr::summarise(x,max=max(age),min=min(age),mean=mean(age))
summary(x$age)
age_count = dplyr::count(x,age)

age_countP <-
  ggplot(age_count, aes(x = age, y = n))+
  geom_bar(stat = "identity")+
  labs(title = "ユーザの年齢分布")


##5歳刻み
#ヒストグラム
age_count5 <-
  ggplot(x, aes(x = age))+
  geom_histogram(binwidth=5, colour="white")+
  labs(title = "ユーザの年齢分布")

age_countP
age_count5

#円グラフ
age_freq5 = cut(x$age, breaks=seq(10,70,5))
age_tab5 = table(age_freq5)
age_tab5%>%
  kable()
age_freq10 = cut(x$age, breaks=seq(10,70,10))
age_tab10 = table(age_freq10)

par(mfrow=c(1,2)) 
pie(age_tab5, labels=c("11-15","16-20","21-25","26-30","31-35","36-40","41-45","46-50","51-55","56-60","61-65","66-70"), clockwise=T, border="#ffffff", main="年齢分布", col=topo.colors(16))

pie(age_tab10, labels=c("11-20","21-30","31-40","41-50","51-60","61-70"), clockwise=T, border="#ffffff", main="年齢分布", col=topo.colors(8))
```

#職業
```{r}
#job_code

job_count <- dbGetQuery(con,"
select
	distinct(S.job_code),
	J.job,
	count(S.job_code)
from
	processed.tv_sample_p_cv as S
left join
	processed.job_mst as J	
on
	J.job_code = S.job_code
group by
	S.job_code,
	J.job
order by
  S.job_code;")
job_count%>%
  kable()

#ヒストグラム
job_countP <-
  ggplot(job_count, aes(x = reorder(job, -count), y = count))+
  geom_bar(stat = "identity", col=topo.colors(14), fill = topo.colors(14))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  +
  labs(title = "職業") 

job_countP

#円グラフ
job_count <- dbGetQuery(con,"
select
	distinct(S.job_code),
	J.job,
	count(S.job_code)
from
	processed.tv_sample_p_cv as S
left join
	processed.job_mst as J	
on
	J.job_code = S.job_code
group by
	S.job_code,
	J.job
order by
  count(S.job_code) desc;")

pie(job_count$count, labels=head(job_count$job,3) ,clockwise=T, border="#ffffff", main="職業", col=topo.colors(14), radius = 1)
```


