---
title: "nfm"
author: "Midori Omura"
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4.5
    theme: sandstone 
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE)
source("/home/midori/competition/psql.R")
source("/home/midori/competition/name_data.R")
#source("/home/midori/competition/name_target.R")
```

```{r setup2,include=FALSE}
library(tidyverse)
library(lubridate)
library(dbplyr)
library(dbplot)
library(RPostgreSQL)
library(ggforce)
library(DT)
library(NMF)
library(knitr)
library(minerva)
library(GGally)
library(ggalluvial)
library(gridExtra)
#install.packages("minerva")

theme_set(theme_bw(base_family = "HiraKakuPro-W3"))
```


```{r get data}
orgn <- con %>% 
  tbl(from = dbplyr::in_schema("edit", "tv_orgn_program_2")) 
tmp <- con %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_orgn_p_cv")) 
program <- con %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_program")) 
ban <- con %>% 
  tbl(from = dbplyr::in_schema("processed", "bancluster_mst")) 
ban1 <- con %>% 
  tbl(from = dbplyr::in_schema("sub_mst", "ban_code1_mst")) 
ban2 <- con %>% 
  tbl(from = dbplyr::in_schema("sub_mst", "ban_code2_mst")) 
prof_data <- con %>% 
  tbl(from = dbplyr::in_schema("processed", "profiledata"))
prof_mst <- con %>% 
  tbl(from = dbplyr::in_schema("processed", "profilemaster"))
prof <- prof_data %>% 
  left_join(prof_mst, by = c("qu_genre_code", "question_code", "answer_code"))
sta <- con %>% 
  tbl(from = dbplyr::in_schema("processed", "sta_mst"))

#watch_rate <- read_csv("data/processed/watch_rate.csv")

res <- read_rds("/home/midori/competition/results_nmf.rds")
```

```{r what is included in res}
smr <- sapply(res, function(x) summary(x)) %>% 
  t() %>% 
  as.data.frame()
smr %>% 
  kable()
```

```{r plot1}
smr1 <- smr %>% 
   ggplot(aes(x = rank, y=residuals))+
   geom_line()+
  theme_bw()+
  theme(axis.text=element_text(size=12),
        axis.title = element_text(size=15))
```

```{r mic cor}
# mic <- sapply(res, function(x) {
#   a <- mine(basis(x))$MIC
#   diag(a) <- 0
#   return( max(abs(a)) )
#   })

cor <- sapply(res, function(x) {
  a <- cor(basis(x))
  diag(a) <- 0
  return( max(abs(a)) )
  })
# smr <- smr %>% 
#   mutate(cor =  cor,
#          mic = mic)
```

```{r plot2}
 smr2<- smr %>% 
   ggplot(aes(rank, cor)) +
   geom_line()+
  theme_bw()+
  theme(axis.text=element_text(size=12),
        axis.title = element_text(size=15))

grid.arrange(smr1, smr2,ncol=2)
```


```{r }
pro_mst <- program %>% 
  count(station_code, program_code, program_name) %>% 
  collect() %>% 
  group_by(program_code) %>% 
  filter(row_number(desc(n)) == 1) %>% 
  mutate(program_name = str_remove_all(program_name, pattern = " "),
         program_name = str_c(station_code, ".", program_name)) %>% 
  dplyr::select(-station_code) 
#pro_mst



```


# 7
```{r top}
basis7 <- basis(res[[5]])

basis7 %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "program_code") %>% 
  as_tibble() %>% 
  gather(topic, value, -program_code) %>% 
  left_join(pro_mst, by = "program_code") %>% 
  group_by(topic) %>% 
  mutate(rank = row_number(desc(value))) %>% 
  filter(rank < 101) %>% 
  dplyr::select( -program_code, -n, -value) %>% 
  spread(topic, program_name) %>% 
  datatable(class = 'cell-border stripe',
            rownames = FALSE,
            extensions = 'FixedColumns',
            options = list(scrollX = TRUE, scrollCollapse = TRUE
  ))
```

```{r}
p_coef7 <- coef(res[[5]]) %>% 
  apply(2, function(x) which(x == max(x))) %>% 
  tibble(topic = .) %>% 
  ggplot(aes(factor(topic)))+
  geom_bar(colour = "blue", fill = "skyblue")
p_coef7
```

```{r}
innov <- prof %>% 
  filter(qu_genre_code == 25, question_code == 4) %>% 
  dplyr::select(house_num, answer, answer_code) %>% 
  collect() %>% 
  mutate(answer = str_remove_all(answer, pattern = " "))

coef7 <- coef(res[[5]])

apply(coef7, 2, function(x) which(x == max(x)) ) %>% 
  data.frame(topic = .) %>% 
  rownames_to_column(var = "house_num") %>% 
  as_tibble() %>% 
  mutate(house_num = as.integer(house_num)) %>% 
  left_join(innov, by = "house_num") %>% 
  drop_na(answer) %>% 
  mutate(answer = fct_reorder(answer, answer_code)) %>% 
  count(topic, answer) %>% 
  ggplot(aes(axis1 = answer, axis2 = topic, y = n)) +
  scale_x_discrete(limits = c("answer", "topic"), expand = c(.1, .05)) +
  geom_alluvium(aes(fill = answer), alpha=.7)+
  scale_fill_viridis_d()+
  geom_stratum()+ 
  geom_text(stat = "stratum", label.strata = TRUE, family = "HiraKakuPro-W3")+
  theme_classic(base_family = "HiraKakuPro-W3")
```

# target
```{r}
 o_num <- o_house$house_num
 o_num %>% as.data.frame()
 o_num1 <-transform(o_num,segment3=c(rep(1,135)))
 colnames(o_num1) <- c("house_num", "segment3")


# apply(coef6, 2, function(x) which(x == max(x)) ) %>% 
#   data.frame(topic = .) %>% 
#   rownames_to_column(var = "house_num") %>% 
#   as_tibble() %>% 
#   mutate(house_num = as.integer(house_num)) %>% 
#   left_join(o_num1, by = "house_num") %>% 
#   drop_na(segment6) %>% 
# #  mutate(answer = fct_reorder(answer, answer_code)) %>% 
#   count(topic, segment6) %>% 
#   ggplot(aes(axis1 = segment6, axis2 = topic, y = n)) +
#   scale_x_discrete(limits = c("segment6", "topic"), expand = c(.1, .05)) +
#   geom_alluvium(aes(fill = factor(topic)), alpha=.7)+
#   scale_fill_viridis_d()+
# #  geom_stratum()+ 
#   geom_text(stat = "stratum", label.strata = TRUE, family = "HiraKakuPro-W3")+
#   theme_classic(base_family = "HiraKakuPro-W3")

o_topic7 <- apply(coef7, 2, function(x) which(x == max(x)) ) %>% 
  data.frame(topic = .) %>% 
  rownames_to_column(var = "house_num") %>% 
  as_tibble() %>% 
  mutate(house_num = as.integer(house_num)) %>% 
  left_join(o_num1, by = "house_num") %>% 
  drop_na(segment3) %>% 
#  mutate(answer = fct_reorder(answer, answer_code)) %>% 
  count(topic, segment3) 
p_target7 <- o_topic7 %>% ggplot(aes(x=topic,y=n))+
  geom_bar(stat=  "identity",colour = "blue", fill = "skyblue")
p_target7
```

```{r}
grid.arrange(p_coef7, p_target7,
             ncol = 2)
```

```{r}
# a_0 でtargetのmaxのtopicでの人数カウント
a_0 <-coef(results_nmf[[5]]) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("house_num") %>% 
  filter(house_num %in% o_num) %>% 
  gather(topic, value, -house_num) %>% 
  group_by(house_num) %>% 
  filter(value ==max(value)) %>% 
  group_by(topic) %>% 
  count(topic)

a_0$topic<-c(1:7)
colnames(a_0)<-c("topic","count")
a_0p<-  a_0 %>% ggplot(aes(x=topic, y=count))+
  geom_bar(stat = "identity")+
  theme_bw()+
    theme(axis.text=element_text(size=12),
          axis.title = element_text(size=15),
        legend.title = element_blank()
        )

b_0 <- coef(results_nmf[[5]]) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("house_num") %>% 
  gather(topic, value, -house_num) %>% 
  group_by(house_num) %>% 
  filter(value ==max(value)) %>% 
  group_by(topic) %>% 
  count(topic)
b_0$topic<-c(1:7)
colnames(b_0)<-c("topic","count")
b_0p<-  b_0 %>% ggplot(aes(x=topic, y=count))+
  geom_bar(stat = "identity")+
  theme_bw()+
    theme(axis.text=element_text(size=12),
          axis.title = element_text(size=15),
        legend.title = element_blank()
        )

c_0 <- coef(results_nmf[[5]]) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("house_num") %>% 
  filter(house_num %in% man) %>% 
  gather(topic, value, -house_num) %>% 
  group_by(house_num) %>% 
  filter(value ==max(value)) %>% 
  group_by(topic) %>% 
  count(topic)
c_0$topic<-c(1:7)
colnames(c_0)<-c("topic","count")

grid.arrange(a_0p, b_0p,ncol=2)
```

```{r max}
a <- coef(results_nmf[[5]]) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("house_num") %>% 
  filter(house_num %in% o_num) %>% 
  dplyr::select(-house_num) %>% 
  apply(2, mean) %>% 
  data.frame(topic = names(.),
             value = .)  
a$topic<-c(1:7)

b <- coef(results_nmf[[5]]) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("house_num") %>% 
  dplyr::select(-house_num) %>% 
  apply(2, mean) %>% #列に対して平均
  data.frame(topic = names(.),
             value = .) 
b$topic<-c(1:7)


man <- data2 %>% 
  filter(sex=="男性") %>% 
  dplyr::select(house_num)  
man<-  as.integer(man$house_num)

c <- coef(results_nmf[[5]]) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("house_num") %>% 
  filter(house_num %in% man) %>% 
  dplyr::select(-house_num) %>% 
  apply(2, mean) %>% 
  data.frame(topic = names(.),
             value = .)
c$topic<-c(1:7)


c %>% 
  ggplot(aes(topic, value))+
  geom_bar(stat = "identity")

# aターゲット b全員 c男性
group<- c(rep("Target",7))
a<-cbind(a,group)

group<- c(rep("Man",7))
b<-cbind(b,group)

group<- c(rep("All",7))
c<-cbind(c,group)

d <- rbind(a,b,c)
d %>% kable

d_p<-d %>% 
  ggplot(aes(topic, value, fill=factor(group)))+
  geom_bar(stat = "identity", position = "dodge")+
  scale_fill_manual(values = c( "#00cbcb","#0000ff","#ff0000"))+
  scale_x_continuous(breaks=seq(0,8,1))+
  theme_bw()+ylim(0,0.0035)+
    theme(axis.text=element_text(size=12),
          axis.title = element_text(size=15),
        legend.title = element_blank()
        )
```

```{r mean_all}
a_1 <- coef(results_nmf[[5]]) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("house_num") %>% 
  filter(house_num %in% o_num) %>% 
  gather(topic, value, -house_num) %>% 
  group_by(house_num) %>% 
  filter(value == max(value)) %>% 
  group_by(topic) %>% 
  summarise(value = mean(value))
a_1$topic<-c(1:7)

b_1 <- coef(results_nmf[[5]]) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("house_num") %>% 
  gather(topic, value, -house_num) %>% 
  group_by(house_num) %>% 
  filter(value == max(value)) %>% 
  group_by(topic) %>% 
  summarise(value = mean(value))
b_1$topic<-c(1:7)

c_1 <- coef(results_nmf[[5]]) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("house_num") %>% 
  filter(house_num %in% man) %>% 
  gather(topic, value, -house_num) %>% 
  group_by(house_num) %>% 
  filter(value == max(value)) %>% 
  group_by(topic) %>% 
  summarise(value = mean(value))
c_1$topic<-c(1:7)

# aターゲット b全員 c男性
group<- c(rep("Target",7))
a_1<-cbind(a_1,group)

group<- c(rep("Man",7))
b_1<-cbind(b_1,group)

group<- c(rep("All",7))
c_1<-cbind(c_1,group)

d_1 <- rbind(a_1,b_1,c_1)
d_1 %>% kable

d_1p<-d_1 %>% 
  ggplot(aes(topic, value, fill=factor(group)))+
  geom_bar(stat = "identity", position = "dodge")+
  scale_fill_manual(values = c( "#00cbcb","#0000ff","#ff0000"))+
  scale_x_continuous(breaks=seq(0,8,1))+
  ylim(0,0.0035)+xlab("cluster number")+
theme_bw()+
    theme(axis.text=element_text(size=12),
          axis.title = element_text(size=15),
          legend.text=element_text(size=12),
          legend.title = element_blank())
grid.arrange(d_p, d_1p, ncol=2)


```

```{r}
```


```{r 7 top10}
basis7 %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "program_code") %>% 
  as_tibble() %>% 
  gather(topic, value, -program_code) %>% 
  left_join(pro_mst, by = "program_code") %>% 
  group_by(topic) %>% 
  # mutate(rank = min_rank(desc(value))) %>% 
  drop_na(program_name) %>% 
  mutate(rank = row_number(desc(value))) %>%
  filter(rank < 6) %>%
  dplyr::select( -program_code, -n, -value) %>% 
  spread(topic, program_name) %>% 
  kable()
  # datatable(class = 'cell-border stripe',
  #           rownames = FALSE,
  #           extensions = 'FixedColumns',
  #           options = list(scrollX = TRUE, scrollCollapse = TRUE
  # ))
```

