---
title: "SAS_new"
author: "Midori Omura"
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4.5
    theme: sandstone 
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE)
```


```{r set_up}
#パッケージのインストールと読み込み
#持ってないパッケージはインストールする
#install.packages("MASS")
library(knitr)
library(DBI)
library(tidyverse)
library(reshape2)
library(dbplot)
library(lubridate)
library(DT)
library(gridExtra)
library(fmsb)
library(corrplot)
library(GGally)
library(graphics)
library(psych)
library(GPArotation)
library(proxy)
library(MASS)
library(ggmosaic)
library(cluster)
library(e1071)
library(ggplot2)
try(dbDisconnect(con))
source("/home/midori/competition/psql.R")
source("/home/midori/competition/name_data2.R")
```

only_all → 全部の回答が一致 →269人  
only_all_sub → 情報特性か購買特性のどちらかで回答一致 →226人  

```{r dataIS}
# only_allだけ抜く
dataIS_new %>% 
  head() %>% 
  kable()

# only_all_subも抜く
dataIS_new_sub %>% 
  head() %>% 
  kable()

dataIS_new %>% count()
dataIS_new_sub %>% count()
```

- dataIS_new → 4443人.  
- dataIS_new_sub → 4217人.  
allだけでやってくよ.  

## 相関行列
```{r dataIS_new 相関行列}
#相関行列の作成
dataIS_new.c <- cor(dataIS_new[,-1])
dataIS_new.c %>% 
  kable()
```
  
## 固有値
```{r dataIS_new 固有値}
eigenIS_new <- eigen(dataIS_new.c)$values
# 固有値
eigenIS_new
```

## 因子数決定
```{r dataIS_new plot}
# Minimum Average Partial, BIC
VSS(dataIS_new[,-1], n=10)
# 平行分析
#fa.parallel(dataIS_new[,-1], main = "")
```  
- MAP:3  
- BIC:7  
- PC:?
- FA:?  
第3固有値までで行ってみる.  
ちょっと平行分析長いのであきらめる.

# 因子分析
***  
データ数が多いため, 最尤法を用いる.  
また心理尺度であるため, 斜交回転 (promax)を行う.  

```{r promax}
dataIS_new <- dataIS_new %>% 
  as.data.frame() 
ml1	<-	fa(r=dataIS_new[,-1],	nfactors=3,	rotate="promax",	fm="ml")
print(ml1)
loadings1 <- ml1$loadings[,1:3]
loadings1<- loadings1[,c(1,3,2)]
 loadings <- 
   data.frame(
     question_num = c(1:18),
     loadings1)
load1 <- ggplot(loadings1, aes(x = question_num, y = ML1)) +
  geom_bar(stat = "identity", position = "identity") + 
  xlim(0,19)+
  labs(x = "question number ")+
  scale_fill_brewer(type ="seq",palette = 1)+ 
  theme_bw()+
  theme(axis.text=element_text(size=12),
        axis.title = element_text(size=15))

load2 <- ggplot(loadings1, aes(x = question_num, y = ML2)) +
  geom_bar(stat = "identity", position = "identity")+
  xlim(0,19)+
  labs(x = "question number ")+
  scale_fill_brewer(type ="seq",palette = 1)+ 
  theme_bw()+
  theme(axis.text=element_text(size=12),
        axis.title = element_text(size=15))

load3 <- ggplot(loadings1, aes(x = question_num, y = ML3)) +
  geom_bar(stat = "identity", position = "identity") +
  xlim(0,19)+
  labs(x = "question number ")+
  scale_fill_brewer(type ="seq",palette = 1)+ 
  theme_bw()+
  theme(axis.text=element_text(size=12),
        axis.title = element_text(size=15))

loadT1 <- ggplot(loadings1, aes(x = ML1, y = ML2, label = question_num)) +
  geom_point() +theme_bw()+ geom_label(position = "nudge" )+
  theme(axis.text=element_text(size=12),
        axis.title = element_text(size=15))

loadT2 <- ggplot(loadings1, aes(x = ML1, y = ML3, label = question_num)) +
  geom_point() +theme_bw()+ geom_label(position = "nudge" )+
  theme(axis.text=element_text(size=12),
        axis.title = element_text(size=15))

loadT3 <- ggplot(loadings1, aes(x = ML2, y = ML3, label = question_num)) +
  geom_point() +theme_bw()+ geom_label(position = "nudge" ) +
  theme(axis.text=element_text(size=12),
        axis.title = element_text(size=15))

# slide 3_SAS
grid.arrange(load1, load2, load3,
             ncol = 3)
# fa faIS1
grid.arrange(load1, load2, load3,
             ncol = 2)

# fa num_SAS
pairsSAS <- ggpairs(loadings1[,-1],  aes(label = loadings1$question_num))+
  theme_bw() +
  theme(axis.text=element_text(size=12),
        axis.title = element_text(size=15),
        strip.background =element_rect(fill = "white", colour = "black"),
        strip.text = element_text(size=10))

pairsSAS <- putPlot(pairsSAS, loadT1, 2, 1)  
pairsSAS <- putPlot(pairsSAS, loadT2, 3, 1)
pairsSAS <- putPlot(pairsSAS, loadT3, 3, 2) 

pairsSAS
```

## biplot
```{r biplot}
scores1 <- ml1$scores[,1:3]
scores1 <- scores1[,c(1,3,2)]
scores1 <- data.frame(scores1)
rownames(scores1) <- dataIS_new$house_num
scores1 <- cbind(scores1, index, genreIS, age_index)
colnames(scores1) <- c("ML1","ML2","ML3","index","genreIS", "age_index")
#scores1_new <- cbind(scores1, index, genreIS, age_index)

```

## VRラベル付け
```{r}
# colored by IS segmemnt
IS12 <-ggplot(scores1, aes(x=ML1, y=ML2, col=genreIS)) +
  geom_point(size = 1)+theme_bw()+
  scale_color_manual(values = c( "#802AE8","#E82C0C","#2CC6FF","#FF0DFF","#C46FFF","#294BE8"))
IS13 <-ggplot(scores1, aes(x=ML1, y=ML3, col=genreIS)) +
  geom_point(size = 1)+theme_bw()+
  scale_color_manual(values = c( "#802AE8","#E82C0C","#2CC6FF","#FF0DFF","#C46FFF","#294BE8"))
IS23 <-ggplot(scores1, aes(x=ML2, y=ML3, col=genreIS)) +
  geom_point(size = 1)+theme_bw()+
  scale_color_manual(values = c( "#802AE8","#E82C0C","#2CC6FF","#FF0DFF","#C46FFF","#294BE8"))
grid.arrange(IS12, IS13, IS23,
             ncol = 2)
```

# 距離行列
```{r dist}
dE <- proxy::dist(ml1$scores, method="Euclidean")
head(dE,5)
dE1 <- as.matrix(dE)
#write.csv(dES1, file= "/home/miidri/competition/dEI1.csv")
rownames(dE1) <- dataIS_new$house_num
colnames(dE1) <- dataIS_new$house_num
dE1[1:5,1:5]
```

# クラスタリング
## k-medoid

どちらともいえないでクラスタ1つ生成されていたので, 今回は1個減らしてみようかな, てきな.  
6にすると真ん中にもう1クラスタできた.
```{r pam}
set.seed(4410)
rownames(scores1)<- house_num
scores1_new<- scores1[,c(1,3,2)]
colnames(scores1_new)<- c("ML1", "ML2","ML3")

pam5 <- pam(scores1_new[1:3], 5)
#pam6 <- pam(scores1_new[1:3], 6)

# 全容
pam5$data %>% 
  as_tibble() %>% 
  mutate(clust = pam6$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  # geom_density_2d()+
  geom_point(size=.5, alpha = .5)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  theme_bw()
# クラスタ別
pam5$data %>% 
  as_tibble() %>% 
  mutate(clust = pam5$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  # geom_density_2d()+
  geom_point(size=.5, alpha = .5)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  facet_wrap(~clust)+
  theme_bw()
clus5 <- pam5$clustering
clus5 <- data.frame(clus5)
clus5 <- cbind(scores1_new, clus5)
```


## 特徴
```{r medoids}
rownames(scores1_new)<- house_num

pam5$medoids # とりあえず6個のmedoidみてみる
#pamIS$id.med
medoid <- pam5$medoids %>% 
  rownames() %>% 
  as.integer() # medoidのhouse_numだけ格納
IS <- dataIS_new %>% 
  filter(house_num
    %in% medoidIS) %>% 
  left_join(tibble(house_num = medoidIS,
                   clust = 1:5),
            by = "house_num") %>% 
  arrange(clust)

IS %>% 
  gather(question, answer, -clust, -house_num) %>% 
   mutate(question = as.integer(question)) %>% 
  #        type = str_sub(question, 1, 1),
  #        number = if_else(type == "S", number + 9L, number)) %>% 
  ggplot(aes(question, answer))+
  geom_bar(stat = "identity")+
  facet_wrap(~clust)+ 
  labs(x = "question number ")+
  ylim(0,5) +
  xlim(1,19)+
  theme_bw()+
  theme(strip.background =element_rect(fill = "white", colour = "black"),
        axis.text=element_text(size=12),
        axis.title = element_text(size=15))
```

```{r cross5}
result5 <- pam5$clustering #clusIS の clusIS と同じ
cross5 <- xta:bs(~genreIS + result5) 
cross5 %>% 
  kable()
plot(cross5,col=c("pink",  "orange", "yellow", "lightgreen",  "skyblue")
     ,las=1) #VR情報選択と答え合わせ
```

