---
title: "Distatis"
author: "Midori Omura"
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4.5
    theme: sandstone 
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE)
```

```{r set_up}
#パッケージのインストールと読み込み
#持ってないパッケージはインストールする
targetPackages <- c('knitr','DBI','RPostgreSQL','tidyverse',"reshape2","lubridate","dbplot","DT","gridExtra","fmsb","corrplot","graphics","GGally","psych", "GPArotation","DistatisR") 
newPackages <- targetPackages[!(targetPackages %in% installed.packages()[,"Package"])]
if(length(newPackages)) install.packages(newPackages, repos = "http://cran.us.r-project.org")
for(package in targetPackages) library(package, character.only = T)

source("/home/miidri/competition/psql.R")
source("/home/miidri/competition/data_name.R")
```


```{r make I}
mlI	<-	fa(r=dataI1[,-1],	nfactors=2,	rotate="promax",	fm="ml")

scoresI <- mlI$scores[,1:2]
scoresI <- data.frame(scoresI)
rownames(scoresI) <- dataI$house_num
scoresI <- cbind(scoresI, data2$index, data2$genreIS, data2$age_index)
colnames(scoresI) <- c("ML1","ML2","index","genreIS", "age_index")

dEI <- proxy::dist(mlI$scores, method="Euclidean")
head(dEI)
dEI1 <- as.matrix(dEI)
#write.csv(dEI1, file= "/home/miidri/competition/dEI1.csv")
rownames(dEI1) <- dataI$house_num
colnames(dEI1) <- dataI$house_num
dEI1[1:5,1:5]

```

```{r make S}
mlS	<-	fa(r=dataS1[,-1],	nfactors=3,	rotate="promax",	fm="ml")

scoresS <- mlS$scores[,1:3]
scoresS <- data.frame(scoresS)
rownames(scoresS) <- dataS$house_num
scoresS <- cbind(scoresS, data2$index, data2$genreIS, data2$age_index)
colnames(scoresS) <- c("ML1","ML2","ML3","index","genreIS", "age_index")

dES <- proxy::dist(mlS$scores, method="Euclidean")
head(dES)
dES1 <- as.matrix(dES)
rownames(dES1) <- dataS$house_num
colnames(dES1) <- dataS$house_num
dES1[1:5,1:5]
```

```{r make L}
mlL	<-	fa(r=dataL1[,-1],	nfactors=4,	rotate="promax",	fm="ml")

scoresL <- mlL$scores[,1:4]
scoresL <- data.frame(scoresL)
rownames(scoresL) <- dataL$house_num
scoresL <- cbind(scoresL, data2$index, data2$genreL, data2$age_index)
colnames(scoresL) <- c("ML1","ML3","ML2","ML4","index","genreIS", "age_index")

dEL <- proxy::dist(mlL$scores, method="Euclidean")
head(dEL)
dEL1 <- as.matrix(dEL)
rownames(dEL1) <- dataL$house_num
colnames(dEL1) <- dataL$house_num
dEL1[1:5,1:5]

```

```{r list作成}
Cube <- list(dEI1, dES1, dEL1)
head(Cube)
```

```{r}
testD <- distatis(Cube)
testD
```

