---
title: "クロス集計"
author: "Midori Omura"
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4.5
    theme: sandstone 
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE)
```


```{r set_up}
#パッケージのインストールと読み込み
#持ってないパッケージはインストールする
targetPackages <- c('knitr','DBI','RPostgreSQL','tidyverse',"reshape2","lubridate","dbplot","DT","gridExtra","fmsb","corrplot","graphics","GGally","psych", "GPArotation", "e1071","cluster") 
newPackages <- targetPackages[!(targetPackages %in% installed.packages()[,"Package"])]
if(length(newPackages)) install.packages(newPackages, repos = "http://cran.us.r-project.org")
for(package in targetPackages) library(package, character.only = T)
source("/home/miidri/competition/psql.R")
source("/home/miidri/competition/name_data.R")
source("/home/miidri/competition/name_dist.R")
```

# 表現嗜好 AI
## k-medoid
```{r AI}
set.seed(4410)
pamL <- pam(scoresL[1:4], 6)
# medoidを基にしたプロット
# autoplot(pamL, frame = TRUE, frame.type = 'norm')+
#   theme_bw()+
#  facet_wrap(~cluster)


pamL$data %>% 
  as_tibble() %>% 
  mutate(clust = pamL$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  # geom_density_2d()+
  geom_point(size=.5, alpha = .1)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
#  scale_color_manual(values = c( "#ff0000","#0000ff","#ffcc99","#99cbcb","#ff99cc","#00cbcb"))+
  facet_wrap(~clust)+
  theme_bw()

pamL$data %>% 
  as_tibble() %>% 
  mutate(clust = pamL$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  # geom_density_2d()+
  geom_point(size=.5, alpha = .1)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  theme_bw()
  
clusL <- pamL$clustering
clusL <- data.frame(clusL)
clusL <- cbind(scoresL, clusL) 
# せっかくだからもとの因子に落としてみた
# ggplot(clusL, aes(x=ML1, y=ML2, col=clusL)) +
#   geom_point(size = 1)+theme_bw()
```

## cross
```{r crossAI}
resultAI <- pamL$clustering #clusL の clusL と同じ
segment2 <- data2$genreIS # 情報選択の正解ラベル
segment1 <- data2$genreL #表現嗜好の正解ラベル

# ctblL <- table(segment1, resultAI)
# ctblL %>% 
#   kable()

crossAI <- xtabs(~resultAI + segment1) 
crossAI %>% 
  kable()
plot(crossAI,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1) # VR表現嗜好と答え合わせ
```

## 特徴
```{r medoids AI}
pamL$medoids # とりあえず6個のmedoidみてみる

medoidL <- pamL$medoids %>% 
  rownames() %>% 
  as.integer() # medoidのhouse_numだけ格納

L <- dataL1 %>% 
  filter(house_num %in% medoidL) %>% 
  left_join(tibble(house_num = medoidL,
                   clust = 1:6),
            by = "house_num") %>% 
  arrange(clust)
z = seq(1, 30) # Lを順番に並べるため.

L %>% 
  gather(question, answer, -clust, -house_num) %>% 
  mutate(question = as.integer(str_sub(question, 2,-1))) %>% 
  ggplot(aes(question, answer))+
  geom_bar(stat = "identity")+
  facet_wrap(~clust)+ 
  ylim(0,5)+
  xlim(1,30)+
  theme_bw()

L %>% kable()
```

# 情報選択 SAS
## k-medoid
```{r pam SAS}
set.seed(4410)
pamIS <- pam(scoresIS[1:3], 6)
# medoidを基にしたプロット
# autoplot(pamIS, frame = TRUE, frame.type = 'norm')+
#   theme_bw()
pamIS$data %>% 
  as_tibble() %>% 
  mutate(clust = pamIS$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  # geom_density_2d()+
  geom_point(size=.5, alpha = .1)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  facet_wrap(~clust)+
  theme_bw()

pamIS$data %>% 
  as_tibble() %>% 
  mutate(clust = pamIS$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  # geom_density_2d()+
  geom_point(size=.5, alpha = .1)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  theme_bw()

clusIS <- pamIS$clustering
clusIS <- data.frame(clusIS)
clusIS <- cbind(scoresIS, clusIS)
# せっかくだからもとの因子に落としてみた
# ggplot(clusIS, aes(x=ML1, y=ML2, col=clusIS)) +
#   geom_point(size = 1)+theme_bw()
```

## cross
```{r crossSAS}
resultSAS <- pamIS$clustering #clusIS の clusIS と同じ

# ctblIS <- table(segment2, resultSAS)
# ctblIS %>% 
#   kable()
# ctblIS1 <- table(segment1, resultSAS)
# ctblIS1 %>% 
#   kable()

crossSAS <- xtabs(~resultSAS + segment2) 
crossSAS %>% 
  kable()
plot(crossSAS,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1) #VR情報選択と答え合わせ
```

## 特徴
```{r medoids}
pamIS$medoids # とりあえず6個のmedoidみてみる

medoidIS <- pamIS$medoids %>% 
  rownames() %>% 
  as.integer() # medoidのhouse_numだけ格納

IS <- dataIS1 %>% 
  filter(house_num %in% medoidIS) %>% 
  left_join(tibble(house_num = medoidIS,
                   clust = 1:6),
            by = "house_num") %>% 
  arrange(clust)

IS %>% 
  gather(question, answer, -clust, -house_num) %>% 
  mutate(number = as.integer(str_sub(question, 2,-1)),
         type = str_sub(question, 1, 1),
         number = if_else(type == "S", number + 9L, number)) %>% 
  ggplot(aes(number, answer))+
  geom_bar(stat = "identity")+
  facet_wrap(~clust)+ 
  labs(x = "question number ")+
  ylim(0,5) +
  xlim(1,18)+
  theme_bw()


IS %>% kable()
```

# VRラベル クロス分析
```{r crossVR}
cross0 <- xtabs(~segment1 + segment2) 
cross0 %>% 
  kable()
plot(cross0,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1)
#ctbl <- table(segment1, segment2) 
#ctbl <- data.frame(ctbl)
# ggplot だとあまりx軸が均一でよく伝わらないかなぁ
# cross1 <- ggplot(ctbl, aes(x=segment2, y=Freq, fill=segment1)) +
#   geom_bar(stat = "identity", position="fill") + theme_bw()
# cross1
# cross2 <- ggplot(ctbl, aes(x=segment1, y=Freq, fill=segment2)) +
#   geom_bar(stat = "identity", position="fill") + theme_bw()
# cross2
```

# 情報選択・表現選択 クロス分析
```{r cross IS L}
cross3 <- xtabs(~resultSAS + resultAI)
cross3 %>% 
  kable()
plot(cross3,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1)
#ctbl0 <- table(resultSAS, resultAI)
#ctbl0 <- data.frame(ctbl0)
# cross4 <- ggplot(ctbl0, aes(x=resultSAS, y=Freq, fill=resultAI)) +
#   geom_bar(stat = "identity", position="fill") + theme_bw()
# cross4
# cross5 <- ggplot(ctbl0, aes(x=resultAI, y=Freq, fill=resultsSAS)) +
#   geom_bar(stat = "identity", position="fill") + theme_bw()
# cross5
```


# 付録
## レーダーチャートL
```{r}
#install.packages("fmsb")
library(fmsb)
LL <- L[-32]
LL <- LL[-1]
rownames(LL) <- medoidL
# LL <- t(LL) %>% 
#   data.frame()
#ラベルの設定,データの行名を取得
vLabel <- colnames(LL)
lLabel <- rownames(LL[-1:-2,])

####radarchartの設定#####
#centerzero = TRUEで中心が0
#axistype:軸基準設定,0:無し, 1:割合, 2:実数, 3:割合,実数, 4:最大を1, 5:最大を1,実数
#seg:分割数
#plty:線の種類
#vlcex:ラベルの大きさ

maxmin <- data.frame(
 L1=c(5,0),
 L2=c(5,0),
 L3=c(5,0),
 L4=c(5,0),
 L5=c(5,0),
 L6=c(5,0),
 L7=c(5,0),
 L8=c(5,0),
 L9=c(5,0),
 L10=c(5,0),
 L11=c(5,0),
 L12=c(5,0),
 L13=c(5,0),
 L14=c(5,0),
 L15=c(5,0),
 L16=c(5,0),
 L17=c(5,0),
 L18=c(5,0),
 L19=c(5,0),
 L20=c(5,0),
 L21=c(5,0),
 L22=c(5,0),
 L23=c(5,0),
 L24=c(5,0),
 L25=c(5,0),
 L26=c(5,0),
 L27=c(5,0),
 L28=c(5,0),
 L29=c(5,0),
 L30=c(5,0))
LL <- rbind(maxmin, LL)

radarchart(LL, axistype = 2, seg = 5, plty = 1, vlcex = 1.5,
           centerzero = TRUE, vlabels = vLabel)
```

# デモグラフィック属性
## 男女
```{r}
cross10 <- xtabs(~data2$sex + resultAI)
cross10 %>% 
  kable()
plot(cross10,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1, main="",cex.axis=1.3, xlab = "sex")

cross11 <- xtabs(~data2$sex + resultSAS)
cross11 %>% 
  kable()
plot(cross11,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1, main="",cex.axis=1.3)
```


## 男女・未既婚
```{r}
cross6 <- xtabs(~index + resultAI)
cross6 %>% 
  kable()
plot(cross6,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1, main="",cex.axis=1.3)

cross7 <- xtabs(~index + resultSAS)
cross7 %>% 
  kable()
plot(cross7,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1, main="",cex.axis=1.3)
```

## 年齢
```{r}
cross8 <- xtabs(~age_index + resultAI)
cross8 %>% 
  kable()
plot(cross8,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1, main="",cex.axis=1.3)

cross9 <- xtabs(~ age_index+ resultSAS)
cross9 %>% 
  kable()
plot(cross9,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1, main="",cex.axis=1.3)
```

# plot まとめ
```{r 白黒用}
pam1 <- pamL$data %>% 
  as_tibble() %>% 
  mutate(clust = pamL$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  # geom_density_2d()+
  geom_point(size=.1, alpha = 1)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  scale_color_manual(values = c( "#000000","#000000","#000000","#000000","#000000","#000000"))+
  facet_wrap(~clust)+
  theme_bw()+
  theme(axis.text=element_text(size=10),
        legend.position = 'none',
        strip.background =element_rect(fill = "transparent", colour = "black"),
        strip.text = element_text(size=10))


pam2 <- pamL$data %>% 
  as_tibble() %>% 
  mutate(clust = pamL$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  scale_color_manual(values = c( "#000000","#000000","#000000","#000000","#000000","#000000"))+
  # geom_density_2d()+
  geom_point(size=.1, alpha = 1)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  theme_bw()+
  theme(axis.text=element_text(size=10),
        legend.position = 'none')

# SAS クラスタリング結果
pam3 <- pamIS$data %>% 
  as_tibble() %>% 
  mutate(clust = pamIS$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  scale_color_manual(values = c( "#000000","#000000","#000000","#000000","#000000","#000000"))+
  # geom_density_2d()+
  geom_point(size=.1, alpha = 1)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  facet_wrap(~clust)+
  theme_bw()+
  theme(axis.text=element_text(size=10),
        legend.position = 'none',
        strip.background =element_rect(fill = "transparent", colour = "black"),
        strip.text = element_text(size=10))


pam4 <- pamIS$data %>% 
  as_tibble() %>% 
  mutate(clust = pamIS$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  scale_color_manual(values = c( "#000000","#000000","#000000","#000000","#000000","#000000"))+
  # geom_density_2d()+
  geom_point(size=.1, alpha = 1)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  theme_bw()+
  theme(axis.text=element_text(size=10),
        legend.position = 'none')

grid.arrange(pam2, pam1, ncol = 2)
grid.arrange(pam4, pam3, ncol = 2)

# AI medoid
med1 <- L %>% 
  gather(question, answer, -clust, -house_num) %>% 
  mutate(question = as.integer(str_sub(question, 2,-1))) %>% 
  ggplot(aes(question, answer))+
  geom_bar(stat = "identity")+
  facet_wrap(~clust)+ 
  ylim(0,5)+
  xlim(1,30)+
  theme_bw()+
  theme(axis.text=element_text(size=10),
        strip.background =element_rect(fill = "white", colour = "black"),
        strip.text = element_text(size=10))

# SAS medoids
med2 <-IS %>% 
  gather(question, answer, -clust, -house_num) %>% 
  mutate(number = as.integer(str_sub(question, 2,-1)),
         type = str_sub(question, 1, 1),
         number = if_else(type == "S", number + 9L, number)) %>% 
  ggplot(aes(number, answer))+
  geom_bar(stat = "identity")+
  facet_wrap(~clust)+ 
  labs(x = "question number ")+
  ylim(0,5) +
  xlim(1,18)+
  theme_bw()+
  theme(axis.text=element_text(size=10),
        strip.background =element_rect(fill = "white", colour = "black"),
        strip.text = element_text(size=10))

grid.arrange(med1, med2, ncol = 2)

 par(mfrow=c(1,2))

 ggplot(data = data2) +
   geom_mosaic(aes(x = product(sex_data, resultAI), fill=sex_data), na.rm=TRUE) + 
  labs(x="label(A・I)", y="性別")+
  theme_bw()+
  theme(legend.position = 'none',
        axis.text=element_text(size=12),
        axis.title = element_text(size=15))
 
 
# AI VR表現嗜好と答え合わせ
plot(crossAI,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1, main="",cex.axis=1.3) 
# SAS VR情報選択と答え合わせ
plot(crossSAS,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1, main="",cex.axis=1.3) 
# 男女AI
plot(cross10,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=1,las=1, main="",cex.axis=1.3, xlab = "sex")
# AISAS モザイク
plot(cross3,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     , cex.lab=1,las=1, main="",cex.axis=1.3)

data2 <- cbind(data2, resultAI, resultSAS)
mosaic1 <- ggplot(data = data2) +
   geom_mosaic(aes(x = product(genreL, resultAI), fill=genreL), na.rm=TRUE) + 
  labs(x="label(A・I)", y="表現嗜好")+
  theme_bw()+
  theme(legend.position = 'none',
        axis.text=element_text(size=12),
        axis.title = element_text(size=15))

mosaic2 <- ggplot(data = data2) +
   geom_mosaic(aes(x = product(genreIS, resultSAS), fill=genreIS), na.rm=TRUE) + 
  labs(x="label(A・I)", y="情報選択")+
  theme_bw()+
  theme(legend.position = 'none',
        axis.text=element_text(size=12),
        axis.title = element_text(size=15))

mosaic3 <- ggplot(data = data2) +
   geom_mosaic(aes(x = product(sex_data, resultAI), fill=sex_data), na.rm=TRUE) + 
  labs(x="label(S・A・S)", y="性別")+
  theme_bw()+
  theme(legend.position = 'none',
        axis.text=element_text(size=12),
        axis.title = element_text(size=15))

mosaic4 <- ggplot(data = data2) +
   geom_mosaic(aes(x = product(resultSAS, resultAI), fill=resultSAS), na.rm=TRUE) + 
  labs(x="label(A・I)", y="label(S・A・S)")+
  theme_bw()+
  theme(legend.position = 'none',
        axis.text=element_text(size=12),
        axis.title = element_text(size=15))


grid.arrange(mosaic1, mosaic2, ncol = 2)
grid.arrange(mosaic3, mosaic4, ncol = 2)

```

```{r カラー用}
pamL$data %>% 
  as_tibble() %>% 
  mutate(clust = pamL$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  # geom_density_2d()+
  geom_point(size=.2, alpha = .5)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
#  scale_color_manual(values = c( "#000000","#000000","#000000","#000000","#000000","#000000"))+
  facet_wrap(~clust)+
  theme_bw()

pamL$data %>% 
  as_tibble() %>% 
  mutate(clust = pamL$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  # geom_density_2d()+
  geom_point(size=.2, alpha = .5)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  theme_bw()

# SAS クラスタリング結果
pamIS$data %>% 
  as_tibble() %>% 
  mutate(clust = pamIS$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  # geom_density_2d()+
  geom_point(size=.2, alpha = .5)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  facet_wrap(~clust)+
  theme_bw()

pamIS$data %>% 
  as_tibble() %>% 
  mutate(clust = pamIS$clustering) %>% 
  ggplot(aes(ML1, ML2, colour = factor(clust), fill=factor(clust)))+
  # geom_density_2d()+
  geom_point(size=.2, alpha = .5)+
  stat_ellipse(geom = "polygon", alpha=.3, type = "norm")+
  theme_bw()


# AI medoid
L %>% 
  gather(question, answer, -clust, -house_num) %>% 
  mutate(question = as.integer(str_sub(question, 2,-1))) %>% 
  ggplot(aes(question, answer))+
  geom_bar(stat = "identity")+
  facet_wrap(~clust)+ 
  ylim(0,5)+
  xlim(1,30)+
  theme_bw()

# SAS medoids
IS %>% 
  gather(question, answer, -clust, -house_num) %>% 
  mutate(number = as.integer(str_sub(question, 2,-1)),
         type = str_sub(question, 1, 1),
         number = if_else(type == "S", number + 9L, number)) %>% 
  ggplot(aes(number, answer))+
  geom_bar(stat = "identity")+
  facet_wrap(~clust)+ 
  labs(x = "question number ")+
  ylim(0,5) +
  xlim(1,18)+
  theme_bw()

# 日本語を使うためのオプション
options(  X11fonts = c(
     "-*-gothic-%s-%s-normal--%d-*-*-*-*-*-*-*"
    ,"-adobe-symbol-*-*-*-*-%d-*-*-*-*-*-*-*"
   ))

# AI VR表現嗜好と答え合わせ
plot(crossAI,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1, main="") 

# SAS VR情報選択と答え合わせ
plot(crossSAS,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1, main="") 

# VR モザイク
#plot(cross0,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
#     ,cex.lab=2,las=1, main="")

# AISAS モザイク
plot(cross3,col=c("pink", "red", "orange", "yellow", "lightgreen",  "skyblue")
     ,cex.lab=2,las=1, main="")

```

# モザイク
```{r}
ggplot(data = data2) +
   geom_mosaic(aes(x = product(sex_data, resultAI), fill=sex_data), na.rm=TRUE) + 
  labs(x="label(A・I)", y="性別")+
  theme_bw()+
  theme(legend.position = 'none',
        axis.text=element_text(size=12),
        axis.title = element_text(size=15))

```

