---
title: "practice"
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4.5
    theme: sandstone
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE)
```


```{r set_up}
#パッケージのインストールと読み込み
#持ってないパッケージはインストールする
targetPackages <- c('knitr','DBI','RPostgreSQL','tidyverse',"reshape2","lubridate","dbplot","DT","gridExtra","fmsb","corrplot","graphics","GGally","psych", "GPArotation") 
newPackages <- targetPackages[!(targetPackages %in% installed.packages()[,"Package"])]
if(length(newPackages)) install.packages(newPackages, repos = "http://cran.us.r-project.org")
for(package in targetPackages) library(package, character.only = T)

source("/home/miidri/competition/psql.R")
source("/home/miidri/competition/data_name.R")
```

```{r norm}
# 標準化って今回意味ある？
MMIscale <- scale(dataI_MM1[,-1])

# 意味あるかわかんないけど, 相関もいちおう
ggpairs(
	dataI_MM1[,-1],
	lower = list(continuous = "density", combo = "box")
	)
```

```{r}

```

