---
title: "profile"
output:
    html_document:
    number_sections: true
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4.5
    theme: sandstone
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)
```


```{r set_up}
#パッケージのインストールと読み込み
#持ってないパッケージはインストールする
targetPackages <- c('knitr','DBI','RPostgreSQL','tidyverse',"reshape2","lubridate","dbplot","DT","gridExtra") 
newPackages <- targetPackages[!(targetPackages %in% installed.packages()[,"Package"])]
if(length(newPackages)) install.packages(newPackages, repos = "http://cran.us.r-project.org")
for(package in targetPackages) library(package, character.only = T)

source("psql.R")

```

```{r get_data}
pro <- con %>% 
  tbl(from = dbplyr::in_schema("processed", "profiledata")) 
mst <- con %>% 
  tbl(from = dbplyr::in_schema("processed", "profilemaster"))

```


#とりあえず
```{r head_pro, result = "asis"}
data <- pro %>% 
  head(100) %>% 
  collect()

master <- mst %>% 
  head(100) %>% 
  collect()

data %>% 
  datatable(style="bootstrap", class="table-condensed", options = list(dom = 'tp',scrollX = TRUE))

master %>% 
  datatable(style="bootstrap", class="table-condensed", options = list(dom = 'tp',scrollX = TRUE))

```


#マスタに質問内容とかありそう

##genre

```{r}
genre <- dbGetQuery(con,"
select 
	distinct(qu_genre_code),
	qu_genre
from
	processed.profilemaster
group by
	qu_genre_code,
	qu_genre;")
genre%>%
  kable()
```
32項目

##question

```{r とりあえず全部の質問 出力無し}
que <- dbGetQuery(con,"
select 
	distinct(question_code),
	qu_genre_code,
	question
from
	processed.profilemaster
group by
	qu_genre_code,
	question_code,
	question
order by 
	qu_genre_code,
	question_code;")
mstIN <- mstIN[,c(2,1,3)]
#head(mstIN) %>%
# kable()
```

## 1 フェース項目（基本特性以外）  
```{r 1}
q1 <- dbGetQuery(con,"
select 
	distinct(question_code),
	question
from
	processed.profilemaster
where
	qu_genre_code = 1
group by
	question_code,
	question
order by 
	question_code;")
q1 %>%
 kable()
```


## 2 普段の生活行動
```{r 1}
  q2 <- dbGetQuery(con,"
select 
	distinct(question_code),
	question
from
	processed.profilemaster
where
	qu_genre_code = 2
group by
	question_code,
	question
order by 
	question_code;")
q2 %>%
 kable()
```




## 25 クラスター分類（ＶＲ区分）
```{r 25}
q25 <- dbGetQuery(con,"
select 
	question_code,
  question,
  answer_code,
  answer       
from
	processed.profilemaster
WHERE
	qu_genre_code = 25
order by 
	question_code,
  answer_code;")

q25 %>%
  kable()
```
